---
apiVersion: serving.kserve.io/v1alpha1
kind: ServingRuntime
metadata:
  annotations:
    argocd.argoproj.io/managed-by: openshift-gitops
    argocd.argoproj.io/sync-wave: "0"
    opendatahub.io/apiProtocol: REST
    opendatahub.io/recommended-accelerators: '["nvidia.com/gpu"]'
    openshift.io/display-name: "vLLM ServingRuntime - GPU"
    opendatahub.io/template-display-name: "vLLM ServingRuntime - GPU"
    opendatahub.io/template-name: vllm-2.16-6144
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
  name: vllm-2.16-6144
  namespace: llm-hosting
  labels:
    component: aiworkshop
    opendatahub.io/dashboard: 'true'
    rht-gitops.com/openshift-gitops: model-serving
spec:
  annotations:
    prometheus.io/path: /metrics
    prometheus.io/port: '8080'
  containers:
    - args:
        - --port=8080
        - --model=/mnt/models
        - --served-model-name=ibm-granite/granite-3.2-8b-instruct
        - --distributed-executor-backend=mp
        - --max-model-len=6144
      command:
        - python
        - '-m'
        - vllm.entrypoints.openai.api_server
      env:
        - name: HF_HOME
          value: /tmp/hf_home
      image: 'quay.io/modh/vllm:rhoai-2.16-cuda'
      name: kserve-container
      ports:
        - containerPort: 8080
          protocol: TCP
      volumeMounts:
        - mountPath: /dev/shm
          name: shm
  multiModel: false
  supportedModelFormats:
    - autoSelect: true
      name: vLLM
  volumes:
    - emptyDir:
        medium: Memory
        sizeLimit: 2Gi
      name: shm
